### ISSUE TITLE
Its not uploading...

### ISSUE THREAD

**Issue by DeveloperNeon** [eraters/NodeJS-Img-Uploader#1]
Error message:
The remote server returned an error: (503) Server Unavailable.

Request URL:
https://img.neon-is.fun/upload

**Comment by DeveloperNeon** [comment]
I just disabled cloudflare ssl (i think at least)
Error message:
The request was aborted: Could not create SSL/TLS secure channel.

Request URL:
https://img.neon-is.fun/upload

**Comment by DeveloperNeon** [comment]
Im currently using my other working image uploader to take this screenshot:
https://i.neon-is.fun/img/3XhUd5vW.png

**Comment by DeveloperNeon** [comment]
> 
> 
> I just disabled cloudflare ssl (i think at least)
> Error message:
> The request was aborted: Could not create SSL/TLS secure channel.
> 
> Request URL:
> https://img.neon-is.fun/upload

back to this, its still having this issue

**Comment by eraters** [comment]
Change it to use http, not https.

**Comment by DeveloperNeon** [comment]
ok

**Comment by DeveloperNeon** [comment]
Error message:
The remote server returned an error: (503) Server Unavailable.

Request URL:
http://img.neon-is.fun/upload

**Comment by eraters** [comment]
Can you send me the actual glitch link?

**Comment by DeveloperNeon** [comment]
It said to point it to: link is in your dms

**Comment by DeveloperNeon** [comment]
Eraters fixed it. Thanks!

**Comment by eraters** [comment]
Resolved
